spring:
    messages:
        encoding: UTF-8
    datasource:
        url: jdbc:h2:file:~/database/testdb;AUTO_SERVER=TRUE;TRACE_LEVEL_FILE=4
        driver-class-name: org.h2.Driver
        username: sa
        password: password
        initialization-mode: always
        schema: classpath:schema.sql
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        properties:
         hibernate.hbm2ddl.import_files: classpath:schema.sql
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: true
                web-allow-others: true
    springdoc:
        api-docs:
            path: /v3/api-docs
        swagger-ui:
            path: /swagger-ui.html
            enable: true
        show-actuator: true
        packages-to-scan: com.example.demo.architecture.infrastructure.entrypoints.receivers.controller
server:
    port: 8080
